name: lint
on: [push, pull_request]
jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: go get
      run: go get ./...
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
