name: lint
on: [push, pull_request]
jobs:
  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Get go dependancies
      run: go get ./...
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run golangci-lint
      uses: actions-contrib/golangci-lint@v1
